_format_version: "3.0"
_transform: true

services:
  - name: n8n-webhook
    url: http://n8n:5678
    routes:
      - name: n8n-webhook-route
        hosts: [api.helix.local]
        paths: ["/sap/hooks"]
        strip_path: true
        methods: ["POST","GET","OPTIONS"]
        protocols: ["http","https"]
        plugins:
          - name: cors
            config:
              origins: ["https://n8n.helix.local","https://api.helix.local"]
              methods: ["GET","POST","OPTIONS"]
              headers: ["Content-Type","Authorization"]
              credentials: false
              max_age: 3600
          - name: rate-limiting
            config:
              minute: 120
              policy: local

# Phase 2 (OIDC via Keycloak) — example plugin (uncomment when Keycloak is ready)
# plugins:
#   - name: oidc
#     config:
#       issuer: "https://keycloak.helix.local/realms/helix"
#       client_id: "kong"
#       client_secret: "REPLACE_ME"
#       scopes: ["openid","profile","email"]
#       bearer_only: true
