tls:
  certificates:
    - certFile: "/etc/traefik/certs/helix-do-local.pem"
      keyFile: "/etc/traefik/certs/helix-do-local-key.pem"

http:
  routers:
    n8n:
      rule: "Host(`n8n.helix.local`)"
      entryPoints:
        - websecure
      service: n8n-service
      tls: {}

    vault:
      rule: "Host(`vault.helix.local`)"
      entryPoints:
        - websecure
      service: vault-service
      tls: {}

    ollama:
      rule: "Host(`ollama.helix.local`)"
      entryPoints:
        - websecure
      service: ollama-service
      tls: {}
    
    kong:
      rule: "Host(`api.helix.local`)"
      entryPoints:
        - websecure
      service: kong-service
      tls: {}

  services:
    n8n-service:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

    vault-service:
      loadBalancer:
        servers:
          - url: "http://vault:8200"

    ollama-service:
      loadBalancer:
        servers:
          - url: "http://ollama-turbo:11434"

    kong-service:
      loadBalancer:
        servers:
          - url: "http://kong:8000"


